#!/bin/bash

# Helps to update the formulae in this repository (those with the 'tw-' prefix),
# that are based on counterparts from the official Homebrew repository, as the
# latter get updated. Also keeps track of the reference formulae with commit ID
# and commit date.
#
# Usage:
#
#   update-formulae {--sync|--update}

# Configuration.
versions_file=VERSIONS
formula_prefix=tw-

# Exits program with error message.
die() {
  echo "Error: ${*}" >&2
  exit 1
}

# Tests if an array contains a value.
in-array() {
  local item value="${1}"

  shift
  for item in "${@}" ; do
    [[ "${item}" = "${value}" ]] \
      && return 0
  done
  return 1
}

# Process arguments.
do_update=
case "${#}:${1}" in
  1:--sync)
    # Default mode of operation.
    ;;
  1:--update)
    do_update=t
    ;;
  *)
    die "Usage: ${0##*/} {--sync|--update}"
    ;;
esac

# Determine our formula directory ('Formula' from repository root).
self="${0}"
[[ "${self}" = /* ]] \
  || self="${PWD}/${self}"
repo_dir="${self%/*}/.."
repo_dir="$(cd "${repo_dir}" && pwd)"
formula_dir="${repo_dir}/Formula"
[[ -n "${formula_dir}" && -d "${formula_dir}" && -r "${formula_dir}" ]] \
  || die "Expected '${formula_dir}' to be a readable directory."
versions_path="${repo_dir}/${versions_file}"
[[ -f "${versions_path}" && -r "${versions_path}" ]] \
  || die "Expected '${versions_path}' to be a readable file."

# Determine Homebrew prefix.
homebrew_prefix="$(brew --prefix)"
[[ -n "${homebrew_prefix}" && -d "${homebrew_prefix}" ]] \
  || die "Failed to determine Homebrew prefix."

# Make sure versions file has no unstaged changes.
versions_dirty="$(git -C "${repo_dir}" diff-files -- "${versions_file}")"
[[ "${?}" -eq 0 ]] \
  || die "Failed to determine status of '${versions_path}'."
[[ -z "${versions_dirty}" ]] \
  || die "Cannot proceed due to unstaged changes in '${versions_path}'."

# Scan our formula directory for formulae.
repo_formulae=()
for formula_file in "${formula_dir}/${formula_prefix}"*.rb ; do
  # Skip non-existent source (e.g. when no file matches).
  [[ -e "${formula_file}" ]] \
    || continue

  # Extract formula name from file name and add to list of repository formulae.
  formula_name="${formula_file##*/}"
  formula_name="${formula_name%.rb}"
  repo_formulae+=("${formula_name}")
done

# Scan versions file for formulae.
file_formulae=()
formulae_meta=()
while IFS= read -r line ; do
  # Skip empty and comment lines.
  [[ -z "${line}" || "${line}" = "#"* ]] \
    && continue

  # Extract formula name and check if matching repository formula exists.
  formula_name="${line%% *}"
  if ! in-array "${formula_name}" "${repo_formulae[@]}" ; then
    echo "Warning: Formula '${formula_name}' exists in versions file, but not in repository." >&2
    continue
  fi

  # Keep a list of formula names and corresponding meta information.
  file_formulae+=("${formula_name}")
  formulae_meta+=("${line}")
done \
  < "${versions_path}"

# Check that all repository formulae are also mentioned in versions file.
for formula_name in "${repo_formulae[@]}" ; do
  if ! in-array "${formula_name}" "${file_formulae[@]}" ; then
    echo "Warning: Formula '${formula_name}' exists in repository, but not in versions file." >&2
  fi
done

# Synchronize, i.e. add possibly missing commit date and change commit ID to the
# one that actually changed the specified formula.
num_updated=0
new_meta=()
echo "Synchronizing versions file to Homebrew repository:"
for info in "${formulae_meta[@]}" ; do
  # Parse the info line.
  formula_name=
  formula_base=
  commit_id=
  commit_date=
  chunk_count=0
  for chunk in ${info} ; do
    let ++chunk_count
    case "${chunk}" in
      base=*)
        [[ "${chunk_count}" -eq 2 ]] \
          || die "Expected 'base' field to be the 2nd in the line."
        formula_base="${chunk#base=}"
        ;;
      commit=*)
        [[ "${chunk_count}" -eq 3 ]] \
          || die "Expected 'commit' field to be the 3rd in the line."
        commit_id="${chunk#commit=}"
        ;;
      date=*)
        [[ "${chunk_count}" -eq 4 ]] \
          || die "Expected 'date' field to be the 4th in the line."
        commit_date="${chunk#date=}"
        ;;
      *=*)
        # Invalid field.
        die "Encountered invalid field '${chunk}' in versions file."
        ;;
      *)
        # No equals sign means we have a formula name.
        [[ "${chunk_count}" -eq 1 ]] \
          || die "Expected formula name to be the 1st in the line."
        formula_name="${chunk}"
        ;;
    esac
  done

  # Check that all required variables are set.
  [[ -n "${formula_name}" && -n "${formula_base}" && -n "${commit_id}" ]] \
    || die "Some required fields are either missing or empty."

  # Query Homebrew repository for true commit ID and date.
  git_args=(
    -C "${homebrew_prefix}"
    log -1 --format=%H@%aI
    "${commit_id}"
    -- "Library/Formula/${formula_base}.rb"
  )
  commit_info="$(git "${git_args[@]}")"
  [[ "${?}" -eq 0 && -n "${commit_info}" ]] \
    || die "Failed to query history of formula '${formula_base}'."
  real_id="${commit_info%%@*}"
  real_date="${commit_info#*@}"

  # Check if there are changes.
  if [[ "${commit_id}" != "${real_id}" || "${commit_date}" != "${real_date}" ]] ; then
    let ++num_updated
    echo "  * ${formula_name}"
  fi

  # Reassemble info line.
  info_prefix="${info% commit=*}"
  new_meta+=("${info_prefix} commit=${real_id} date=${real_date}")
done
if [[ "${num_updated}" -eq 0 ]] ; then
  echo "  (all entries already in sync)"
  [[ -n "${do_update}" ]] \
    || exit 0
else
  echo
  echo "Writing versions file with ${num_updated} updated entries."
  printf "%s\n" "${new_meta[@]}" > "${versions_path}"
  if [[ -n "${do_update}" ]] ; then
    echo "Warning: Cannot proceed with update. Altered versions file needs to be staged/committed first." >&2
  fi
  exit 0
fi

# Update formulae, i.e. check Homebrew repository for changes after recorded
# commit ID, extract old and new version, provide diff and log and alter
# versions file to reflect upcoming changes.
num_updated=0
old_meta=("${new_meta[@]}")
new_meta=()
echo
echo "Updating versions file and formulae from Homebrew repository:"
for info in "${old_meta[@]}" ; do
  # Parse the info line (w/o checks since we just generated these lines).
  chunks=(${info})
  formula_name="${chunks[0]}"
  formula_base="${chunks[1]#base=}"
  old_id="${chunks[2]#commit=}"
  old_date="${chunks[3]#date=}"

  # Query Homebrew repository for most recent commit ID/date prior to 'master'.
  git_args=(
    -C "${homebrew_prefix}"
    log -1 --format=%H@%aI
    master
    -- "Library/Formula/${formula_base}.rb"
  )
  commit_info="$(git "${git_args[@]}")"
  [[ "${?}" -eq 0 && -n "${commit_info}" ]] \
    || die "Failed to query history of formula '${formula_base}'."
  new_id="${commit_info%%@*}"
  new_date="${commit_info#*@}"

  # Reassemble info line.
  info_prefix="${info% commit=*}"
  new_meta+=("${info_prefix} commit=${new_id} date=${new_date}")

  # Check if there are changes and otherwise skip to next entry.
  if [[ "${old_id}" != "${new_id}" ]] ; then
    let ++num_updated
    echo "  * ${formula_name}"
  else
    continue
  fi

  # Add comment about pending change to our own formula and generate files that
  # allow to reconstruct and adapt the change.
  formula_file="${formula_dir}/${formula_name}"
  cat >> "${formula_file}.rb" <<EOF

# Base Homebrew formula '${formula_base}' has changed:
#   * Old commit: ${old_id} (${old_date})
#   * New commit: ${new_id} (${new_date})
#   * See '${formula_name}.up.{OLD,NEW,DIFF,LOG}' for details, incorporate those
#     changes, if applicable, and remove this comment afterwards.
EOF
  git -C "${homebrew_prefix}" \
    show "${old_id}:Library/Formula/${formula_base}.rb" \
    > "${formula_file}.up.OLD"
  git -C "${homebrew_prefix}" \
    show "${new_id}:Library/Formula/${formula_base}.rb" \
    > "${formula_file}.up.NEW"
  git -C "${homebrew_prefix}" \
    diff "${old_id}..${new_id}" -- "Library/Formula/${formula_base}.rb" \
    > "${formula_file}.up.DIFF"
  git -C "${homebrew_prefix}" \
    log -p "${old_id}..${new_id}" -- "Library/Formula/${formula_base}.rb" \
    > "${formula_file}.up.LOG"
  cat < "${formula_file}.up.DIFF" >> "${formula_file}.rb"
done
if [[ "${num_updated}" -eq 0 ]] ; then
  echo "  (all entries already up-to-date)"
else
  echo
  echo "Writing versions file with ${num_updated} updated entries."
  printf "%s\n" "${new_meta[@]}" > "${versions_path}"
fi
